"""empty message

Revision ID: 406a7b1a2473
Revises: c256a8eb452d
Create Date: 2022-02-04 07:18:02.670334

"""
from alembic import op
import sqlalchemy as sa
from flask_login import UserMixin

from sqlalchemy import orm
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()


# revision identifiers, used by Alembic.
revision = '406a7b1a2473'
down_revision = 'c256a8eb452d'
branch_labels = None
depends_on = None
class User(Base):
    __tablename__='user'
    id = sa.Column(sa.String(40), primary_key=True)
    username = sa.Column(sa.String(64), index=True, unique=True)
    password_hash = sa.Column(sa.String(255))

class UserSettings(Base):
    __tablename__='user_settings'
    user_id = sa.Column(sa.String(40), nullable=False, primary_key=True)
    token_duration = sa.Column(sa.Integer, nullable=True)



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('token_duration', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )


    bind = op.get_bind()
    session = orm.Session(bind=bind)
    users = session.query(User).all()
    user_settings = [UserSettings(user_id = x.id, token_duration=(2*24)) for x in users]
    session.add_all(user_settings)
    session.commit()

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_settings')
    # ### end Alembic commands ###
