"""Add delete confirmation phrase to settings

Revision ID: 9ae5e7631641
Revises: ac209bf8f899
Create Date: 2022-02-05 12:06:07.338308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ae5e7631641'
down_revision = 'ac209bf8f899'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('delete_confirmation', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'delete_confirmation')
    # ### end Alembic commands ###
