"""Add last issued token validity to user settings

Revision ID: ac209bf8f899
Revises: 406a7b1a2473
Create Date: 2022-02-05 07:31:39.982356

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'ac209bf8f899'
down_revision = '406a7b1a2473'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('last_issued_token', sa.DateTime(), nullable=True))
    op.add_column('user_settings', sa.Column('last_issued_expiration', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts') as batch_op:
        batch_op.drop_column('last_issued_expiration')
        batch_op.drop_column('last_issued_token')
    # ### end Alembic commands ###
