"""Add more edit commands

Revision ID: c80a48b79d69
Revises: 9ae5e7631641
Create Date: 2022-08-01 10:13:43.302142

"""
from typing import List

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from sqlalchemy import orm

from app.business.datatypes import UpdateFieldType
from app.models import ItemCommandModel, UpdateField, ListCommandModel
from app.utils import get_uuid_str

revision = 'c80a48b79d69'
down_revision = '9ae5e7631641'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    session = orm.Session(bind=bind)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('update_field',
    sa.Column('command_id', sa.String(length=40), nullable=False),
    sa.Column('uuid', sa.String(length=40), nullable=False),
    sa.Column('field', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['command_id'], ['item_command_model.command_id'], ),
    sa.PrimaryKeyConstraint('command_id', 'uuid')
    )
    old_commands : List[ItemCommandModel] = session.query(ItemCommandModel).all()
    old_fields = [UpdateField(x.command_id, UpdateFieldType.DONE.value, get_uuid_str() ) for x in old_commands]
    session.add_all(old_fields)
    session.commit()

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('update_field')
    # ### end Alembic commands ###
